import type { TaskGraphTemplateSummary } from "../../types";

export const FALLBACK_TASK_GRAPH_TEMPLATES: TaskGraphTemplateSummary[] = [
  {
    template_id: "supervisor_worker_synthesizer",
    title: "Supervisor / Worker / Synthesizer",
    summary: "Plan with a supervisor, execute in a worker lane, then synthesize the bounded result.",
    node_count: 3,
    edge_count: 2,
    entry_node_ids: ["node_supervisor"],
    node_kinds: ["supervisor", "worker", "synthesizer"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Structured plan", "Bounded worker report", "Final run summary"],
    validation_hints: ["Check the worker route before dry-run", "Keep handoff artifact-first between worker and synthesizer"],
    constraints: ["Single worker lane", "No silent high-risk writes"],
    preview_graph: {
      title: "Supervisor / Worker / Synthesizer",
      nodes: [
        { node_id: "node_supervisor", kind: "supervisor", label: "Plan", position: { x: 64, y: 120 } },
        { node_id: "node_worker", kind: "worker", label: "Execute", position: { x: 304, y: 120 } },
        { node_id: "node_synth", kind: "synthesizer", label: "Synthesize", position: { x: 544, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_plan_execute", from_node_id: "node_supervisor", to_node_id: "node_worker", edge_type: "context_handoff" },
        { edge_id: "edge_execute_synth", from_node_id: "node_worker", to_node_id: "node_synth", edge_type: "artifact_handoff" },
      ],
    },
  },
  {
    template_id: "fanout_fanin_research",
    title: "Fan-out / Fan-in Research",
    summary: "Branch research workers in parallel, then merge the collected artifacts into one synthesis step.",
    node_count: 4,
    edge_count: 3,
    entry_node_ids: ["node_supervisor"],
    node_kinds: ["supervisor", "worker", "worker", "synthesizer"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Branch research notes", "Merge summary", "Attributed branch outputs"],
    validation_hints: ["Validate every fan-out edge policy", "Keep branch outputs bounded before merge"],
    constraints: ["Parallel branch lanes", "Synthesizer consumes declared artifacts only"],
    preview_graph: {
      title: "Fan-out / Fan-in Research",
      nodes: [
        { node_id: "node_supervisor", kind: "supervisor", label: "Brief", position: { x: 64, y: 120 } },
        { node_id: "node_research_a", kind: "worker", label: "Research A", position: { x: 304, y: 56 } },
        { node_id: "node_research_b", kind: "worker", label: "Research B", position: { x: 304, y: 184 } },
        { node_id: "node_synth", kind: "synthesizer", label: "Merge", position: { x: 544, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_plan_a", from_node_id: "node_supervisor", to_node_id: "node_research_a", edge_type: "fanout_branch" },
        { edge_id: "edge_plan_b", from_node_id: "node_supervisor", to_node_id: "node_research_b", edge_type: "fanout_branch" },
        { edge_id: "edge_merge", from_node_id: "node_research_a", to_node_id: "node_synth", edge_type: "artifact_handoff" },
      ],
    },
  },
  {
    template_id: "code_fix_test_review",
    title: "Code Fix / Test / Review",
    summary: "Separate planning, code changes, test execution, and review into explicit bounded nodes.",
    node_count: 4,
    edge_count: 3,
    entry_node_ids: ["node_plan_fix"],
    node_kinds: ["supervisor", "worker", "validator", "reviewer"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Fix plan", "Code diff", "Test report", "Review report"],
    validation_hints: ["Pin the code worker model", "Keep code-change and review nodes separated"],
    constraints: ["Code changes stay bounded", "Review evidence must survive reload"],
    preview_graph: {
      title: "Code Fix / Test / Review",
      nodes: [
        { node_id: "node_plan_fix", kind: "supervisor", label: "Plan Fix", position: { x: 64, y: 120 } },
        { node_id: "node_apply_fix", kind: "worker", label: "Apply Fix", position: { x: 284, y: 120 } },
        { node_id: "node_test", kind: "validator", label: "Run Tests", position: { x: 504, y: 120 } },
        { node_id: "node_review", kind: "reviewer", label: "Review", position: { x: 724, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_fix", from_node_id: "node_plan_fix", to_node_id: "node_apply_fix", edge_type: "context_handoff" },
        { edge_id: "edge_test", from_node_id: "node_apply_fix", to_node_id: "node_test", edge_type: "artifact_handoff" },
        { edge_id: "edge_review", from_node_id: "node_test", to_node_id: "node_review", edge_type: "artifact_handoff" },
      ],
    },
  },
  {
    template_id: "provider_update_smoke_gate",
    title: "Provider Update / Smoke / Gate",
    summary: "Discover provider changes, run a smoke matrix, and block promotion behind a manual gate.",
    node_count: 3,
    edge_count: 2,
    entry_node_ids: ["node_discover"],
    node_kinds: ["extractor", "validator", "gate"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Provider diff bundle", "Smoke matrix", "Promotion decision record"],
    validation_hints: ["Dry-run should surface blocked provider cases", "Promotion remains gated until review"],
    constraints: ["Human approval before promotion", "No silent external writeback"],
    preview_graph: {
      title: "Provider Update / Smoke / Gate",
      nodes: [
        { node_id: "node_discover", kind: "extractor", label: "Discover", position: { x: 80, y: 120 } },
        { node_id: "node_smoke", kind: "validator", label: "Smoke", position: { x: 320, y: 120 } },
        { node_id: "node_gate", kind: "gate", label: "Gate", position: { x: 560, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_discover_smoke", from_node_id: "node_discover", to_node_id: "node_smoke", edge_type: "artifact_handoff" },
        { edge_id: "edge_smoke_gate", from_node_id: "node_smoke", to_node_id: "node_gate", edge_type: "artifact_handoff" },
      ],
    },
  },
  {
    template_id: "document_extract_analyze_report",
    title: "Document Extract / Analyze / Report",
    summary: "Extract source material, analyze it in a bounded lane, then produce a final report artifact.",
    node_count: 3,
    edge_count: 2,
    entry_node_ids: ["node_extract"],
    node_kinds: ["extractor", "worker", "synthesizer"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Document extract", "Structured analysis", "Final report"],
    validation_hints: ["Check extract node output schema first", "Preserve artifact handoff into the report node"],
    constraints: ["Document path stays bounded", "Report is generated from declared extract artifacts only"],
    preview_graph: {
      title: "Document Extract / Analyze / Report",
      nodes: [
        { node_id: "node_extract", kind: "artifact_source", label: "Extract", position: { x: 80, y: 120 } },
        { node_id: "node_analyze", kind: "worker", label: "Analyze", position: { x: 320, y: 120 } },
        { node_id: "node_report", kind: "synthesizer", label: "Report", position: { x: 560, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_extract_analyze", from_node_id: "node_extract", to_node_id: "node_analyze", edge_type: "artifact_handoff" },
        { edge_id: "edge_analyze_report", from_node_id: "node_analyze", to_node_id: "node_report", edge_type: "artifact_handoff" },
      ],
    },
  },
  {
    template_id: "multimodal_capability_adapter",
    title: "Multimodal Capability Adapter",
    summary: "Probe supported input modes, adapt the contract, and verify explicit multimodal fallback behavior.",
    node_count: 3,
    edge_count: 2,
    entry_node_ids: ["node_probe_input"],
    node_kinds: ["extractor", "worker", "validator"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Capability probe", "Adapted multimodal contract", "Fallback validation report"],
    validation_hints: ["Confirm the target model really supports the intended input mode", "Keep fallback behavior explicit instead of silent degradation"],
    constraints: ["Bound multimodal payload sizes", "Declare fallback paths before live provider execution"],
    preview_graph: {
      title: "Multimodal Capability Adapter",
      nodes: [
        { node_id: "node_probe_input", kind: "extractor", label: "Probe Input", position: { x: 80, y: 120 } },
        { node_id: "node_adapt_contract", kind: "worker", label: "Adapt Contract", position: { x: 320, y: 120 } },
        { node_id: "node_validate_fallback", kind: "validator", label: "Validate Fallback", position: { x: 560, y: 120 } },
      ],
      edges: [
        { edge_id: "edge_probe_adapt", from_node_id: "node_probe_input", to_node_id: "node_adapt_contract", edge_type: "artifact_handoff" },
        { edge_id: "edge_adapt_validate", from_node_id: "node_adapt_contract", to_node_id: "node_validate_fallback", edge_type: "context_handoff" },
      ],
    },
  },
  {
    template_id: "custom_blank_graph",
    title: "Custom Blank Graph",
    summary: "Minimal starter graph with one neutral entry node for custom orchestration authoring.",
    node_count: 1,
    edge_count: 0,
    entry_node_ids: ["node_start_here"],
    node_kinds: ["artifact_source"],
    recommended_provider_ids: [],
    recommended_model_ids: [],
    artifact_expectations: ["Starter graph manifest"],
    validation_hints: ["Rename the seed node before dry-run", "Add at least one downstream worker before fixture execution"],
    constraints: ["Treat this as an authoring scaffold, not a finished workflow"],
    preview_graph: {
      title: "Custom Blank Graph",
      nodes: [
        { node_id: "node_start_here", kind: "artifact_source", label: "Start Here", position: { x: 96, y: 120 } },
      ],
      edges: [],
    },
  },
];
