"""Generate the AstraBridge-owned protocol validators and type projections.

The JSON Schema under ``astrabridge_sidecar.protocol.schema`` is the only
business-schema source.  This script deliberately emits deterministic,
dependency-free Python and TypeScript projections so CI can fail on drift.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "apps" / "astrabridge-sidecar" / "astrabridge_sidecar" / "protocol" / "schema" / "v1" / "protocol.json"
PY_OUTPUT = REPO_ROOT / "apps" / "astrabridge-sidecar" / "astrabridge_sidecar" / "protocol" / "generated" / "v1.py"
TS_OUTPUT = REPO_ROOT / "apps" / "astrabridge-desktop" / "src" / "astrabridge_protocol" / "generated" / "v1.ts"


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _py_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return "str"
    if schema.get("type") == "string":
        return "str"
    if schema.get("type") == "integer" or schema.get("type") == "number":
        return "int" if schema.get("type") == "integer" else "float"
    if schema.get("type") == "boolean":
        return "bool"
    if schema.get("type") == "array":
        return "list[Any]"
    if schema.get("type") == "object":
        return "dict[str, Any]"
    return "Any"


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if schema.get("type") == "string":
        return "string"
    if schema.get("type") in {"integer", "number"}:
        return "number"
    if schema.get("type") == "boolean":
        return "boolean"
    if schema.get("type") == "array":
        return f"Array<{_ts_type(dict(schema.get('items') or {}))}>"
    if schema.get("type") == "object":
        return "Record<string, unknown>"
    return "unknown"


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def _schema_enum_values(schema: dict[str, Any], definition_name: str, property_name: str | None = None) -> list[Any]:
    definition = dict(schema["$defs"][definition_name])
    target = definition if property_name is None else dict(definition.get("properties", {}).get(property_name) or {})
    return list(target.get("enum") or [])


def _render_python(schema: dict[str, Any], schema_text: str, digest: str) -> str:
    defs = dict(schema["$defs"])
    vocabularies = {
        "RUN_EVENT_TYPES": _schema_enum_values(schema, "RunEvent", "event_type"),
        "ARTIFACT_STATUSES": _schema_enum_values(schema, "ArtifactStatus"),
        "CONTENT_PART_KINDS": _schema_enum_values(schema, "ContentPart", "kind"),
        "PORT_TYPES": _schema_enum_values(schema, "PortDefinition", "port_type"),
        "PORT_SHAPES": _schema_enum_values(schema, "PortDefinition", "shape"),
        "CAPABILITY_OUTPUT_STATUSES": _schema_enum_values(schema, "CapabilityOutput", "status"),
    }
    lines = [
        "# This file is generated by scripts/generate_protocol_types.py. Do not edit by hand.",
        "from __future__ import annotations",
        "",
        "import json",
        "import re",
        "from datetime import datetime",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
        f"SCHEMA_VERSION = {schema['x-astrabridge-schema-version']!r}",
        f"SCHEMA_ID = {schema['$id']!r}",
        f"SCHEMA_DIGEST = {digest!r}",
        f"SCHEMA = json.loads({schema_text!r})",
        "FORBIDDEN_PROPERTIES = frozenset(str(item).lower() for item in SCHEMA.get('x-forbidden-properties', []))",
        "",
        "class ProtocolValidationError(ValueError):",
        "    pass",
        "",
    ]
    for name, values in vocabularies.items():
        rendered = ", ".join(repr(item) for item in values)
        lines.append(f"{name} = ({rendered},)")
    lines.extend(
        [
            "PROTOCOL_VOCABULARIES = {",
            "    'run_event_types': RUN_EVENT_TYPES,",
            "    'artifact_statuses': ARTIFACT_STATUSES,",
            "    'content_part_kinds': CONTENT_PART_KINDS,",
            "    'port_types': PORT_TYPES,",
            "    'port_shapes': PORT_SHAPES,",
            "    'capability_output_statuses': CAPABILITY_OUTPUT_STATUSES,",
            "}",
            "",
        ]
    )
    for name, definition in defs.items():
        if definition.get("type") != "object":
            if "const" in definition:
                lines.append(f"{name} = Literal[{definition['const']!r}]")
            elif "enum" in definition:
                values = ", ".join(repr(item) for item in definition["enum"])
                lines.append(f"{name} = Literal[{values}]")
            else:
                lines.append(f"{name} = {_py_type(definition)}")
            lines.append("")
            continue
        lines.append(f"class {name}(TypedDict):")
        required = set(definition.get("required") or [])
        properties = dict(definition.get("properties") or {})
        if not properties:
            lines.append("    pass")
        else:
            for field, field_schema in properties.items():
                annotation = _py_type(dict(field_schema))
                marker = "" if field in required else "NotRequired["
                if marker:
                    annotation = f"NotRequired[{annotation}]"
                lines.append(f"    {_safe_name(field)}: {annotation}")
        lines.append("")
    lines.extend(
        [
            "PROTOCOL_DEFINITION_NAMES = tuple(sorted(SCHEMA['$defs']))",
            "",
            "def _resolve(ref: str) -> dict[str, Any]:",
            "    if ref.startswith('#/$defs/'):",
            "        name = ref.rsplit('/', 1)[-1]",
            "        return dict(SCHEMA['$defs'][name])",
            "    raise ProtocolValidationError(f'Unsupported schema reference: {ref}')",
            "",
            "def _is_forbidden_key(key: str) -> bool:",
            "    lowered = key.lower()",
            "    return lowered in FORBIDDEN_PROPERTIES or any(token in lowered for token in ('private_reasoning', 'raw_secret', 'api_key', 'access_token', 'authorization', 'cookie'))",
            "",
            "def _scan_forbidden(value: Any, path: str) -> list[str]:",
            "    if isinstance(value, dict):",
            "        return [error for key, child in value.items() for error in (([f'{path}.{key} contains a forbidden security field'] if _is_forbidden_key(str(key)) else []) + _scan_forbidden(child, f'{path}.{key}'))]",
            "    if isinstance(value, list):",
            "        return [error for index, child in enumerate(value) for error in _scan_forbidden(child, f'{path}[{index}]')]",
            "    return []",
            "",
            "def _validate_node(rule: dict[str, Any], value: Any, path: str) -> list[str]:",
            "    if '$ref' in rule:",
            "        return _validate_node(_resolve(str(rule['$ref'])), value, path)",
            "    errors: list[str] = []",
            "    if 'allOf' in rule:",
            "        for child in list(rule.get('allOf') or []): errors.extend(_validate_node(dict(child), value, path))",
            "    if 'anyOf' in rule:",
            "        branches = [_validate_node(dict(child), value, path) for child in list(rule.get('anyOf') or [])]",
            "        if not any(not branch for branch in branches): errors.append(f'{path} does not match any allowed shape')",
            "    if 'oneOf' in rule:",
            "        branches = [_validate_node(dict(child), value, path) for child in list(rule.get('oneOf') or [])]",
            "        if sum(not branch for branch in branches) != 1: errors.append(f'{path} does not match exactly one allowed shape')",
            "    if 'not' in rule and not _validate_node(dict(rule['not']), value, path): errors.append(f'{path} matches a forbidden shape')",
            "    expected = rule.get('type')",
            "    if expected == 'object':",
            "        if not isinstance(value, dict): return errors + [f'{path} must be an object']",
            "        for field in list(rule.get('required') or []):",
            "            if field not in value: errors.append(f'{path} is missing required field: {field}')",
            "        properties = dict(rule.get('properties') or {})",
            "        for key, child in value.items():",
            "            if key in properties: errors.extend(_validate_node(dict(properties[key]), child, f'{path}.{key}'))",
            "            elif rule.get('additionalProperties') is False: errors.append(f'{path}.{key} is not allowed')",
            "    elif expected == 'array':",
            "        if not isinstance(value, list): return errors + [f'{path} must be an array']",
            "        if 'minItems' in rule and len(value) < int(rule['minItems']): errors.append(f'{path} must contain at least {rule[\"minItems\"]} item(s)')",
            "        if 'items' in rule:",
            "            errors.extend(error for index, item in enumerate(value) for error in _validate_node(dict(rule['items']), item, f'{path}[{index}]'))",
            "    elif expected == 'string':",
            "        if not isinstance(value, str): return errors + [f'{path} must be a string']",
            "        if 'minLength' in rule and len(value) < int(rule['minLength']): errors.append(f'{path} is too short')",
            "        if 'maxLength' in rule and len(value) > int(rule['maxLength']): errors.append(f'{path} is too long')",
            "        if 'pattern' in rule and re.fullmatch(str(rule['pattern']), value) is None: errors.append(f'{path} has an invalid format')",
            "        if rule.get('format') == 'date-time':",
            "            try: datetime.fromisoformat(value.replace('Z', '+00:00'))",
            "            except ValueError: errors.append(f'{path} must be an ISO date-time')",
            "    elif expected == 'integer':",
            "        if isinstance(value, bool) or not isinstance(value, int): return errors + [f'{path} must be an integer']",
            "        if 'minimum' in rule and value < rule['minimum']: errors.append(f'{path} is below the minimum')",
            "    elif expected == 'number':",
            "        if isinstance(value, bool) or not isinstance(value, (int, float)): return errors + [f'{path} must be a number']",
            "    elif expected == 'boolean' and not isinstance(value, bool): return errors + [f'{path} must be a boolean']",
            "    if 'enum' in rule and value not in rule['enum']: errors.append(f'{path} is not an allowed value')",
            "    if 'const' in rule and value != rule['const']: errors.append(f'{path} must equal the schema constant')",
            "    return errors",
            "",
            "def validate_protocol_payload(kind: str, payload: Any) -> Any:",
            "    try: rule = dict(SCHEMA['$defs'][kind])",
            "    except KeyError as exc: raise ProtocolValidationError(f'Unknown protocol definition: {kind}') from exc",
            "    errors = _scan_forbidden(payload, kind) + _validate_node(rule, payload, kind)",
            "    if errors: raise ProtocolValidationError('; '.join(errors))",
            "    return payload",
            "",
            "def validation_verdict(kind: str, payload: Any) -> bool:",
            "    try: validate_protocol_payload(kind, payload)",
            "    except (ProtocolValidationError, TypeError, ValueError): return False",
            "    return True",
            "",
            "__all__ = ['SCHEMA_VERSION', 'SCHEMA_ID', 'SCHEMA_DIGEST', 'SCHEMA', 'RUN_EVENT_TYPES', 'ARTIFACT_STATUSES', 'CONTENT_PART_KINDS', 'PORT_TYPES', 'PORT_SHAPES', 'CAPABILITY_OUTPUT_STATUSES', 'PROTOCOL_VOCABULARIES', 'PROTOCOL_DEFINITION_NAMES', 'ProtocolValidationError', 'validate_protocol_payload', 'validation_verdict']",
            "",
        ]
    )
    return "\n".join(lines)


def _render_typescript(schema: dict[str, Any], schema_text: str, digest: str) -> str:
    defs = dict(schema["$defs"])
    vocabularies = {
        "RUN_EVENT_TYPES": _schema_enum_values(schema, "RunEvent", "event_type"),
        "ARTIFACT_STATUSES": _schema_enum_values(schema, "ArtifactStatus"),
        "CONTENT_PART_KINDS": _schema_enum_values(schema, "ContentPart", "kind"),
        "PORT_TYPES": _schema_enum_values(schema, "PortDefinition", "port_type"),
        "PORT_SHAPES": _schema_enum_values(schema, "PortDefinition", "shape"),
        "CAPABILITY_OUTPUT_STATUSES": _schema_enum_values(schema, "CapabilityOutput", "status"),
    }
    lines = [
        "// This file is generated by scripts/generate_protocol_types.py. Do not edit by hand.",
        "",
        f"export const SCHEMA_VERSION = {json.dumps(schema['x-astrabridge-schema-version'])} as const;",
        f"export const SCHEMA_ID = {json.dumps(schema['$id'])} as const;",
        f"export const SCHEMA_DIGEST = {json.dumps(digest)} as const;",
        f"export const PROTOCOL_SCHEMA = {schema_text.rstrip()} as const;",
        "",
    ]
    for name, values in vocabularies.items():
        rendered = ", ".join(json.dumps(item) for item in values)
        lines.append(f"export const {name} = [{rendered}] as const;")
    lines.extend(
        [
            "export const PROTOCOL_VOCABULARIES = {",
            "  runEventTypes: RUN_EVENT_TYPES,",
            "  artifactStatuses: ARTIFACT_STATUSES,",
            "  contentPartKinds: CONTENT_PART_KINDS,",
            "  portTypes: PORT_TYPES,",
            "  portShapes: PORT_SHAPES,",
            "  capabilityOutputStatuses: CAPABILITY_OUTPUT_STATUSES,",
            "} as const;",
            "",
        ]
    )
    for name, definition in defs.items():
        if definition.get("type") != "object":
            lines.append(f"export type {name} = {_ts_type(definition)};")
            lines.append("")
            continue
        lines.append(f"export interface {name} {{")
        required = set(definition.get("required") or [])
        properties = dict(definition.get("properties") or {})
        if not properties:
            lines.append("  [key: string]: unknown;")
        else:
            for field, field_schema in properties.items():
                optional = "" if field in required else "?"
                lines.append(f"  {_safe_name(field)}{optional}: {_ts_type(dict(field_schema))};")
            lines.append("  [key: string]: unknown;")
        lines.append("}")
        lines.append("")
    lines.extend(
        [
            "export const PROTOCOL_DEFINITION_NAMES = Object.keys(PROTOCOL_SCHEMA.$defs) as Array<keyof typeof PROTOCOL_SCHEMA.$defs>;",
            "export type ProtocolDefinitionName = keyof typeof PROTOCOL_SCHEMA.$defs;",
            "",
            "type JsonSchema = Record<string, any>;",
            "export type ProtocolValidationResult = { ok: boolean; errors: string[] };",
            "",
            "const forbiddenProperties = new Set<string>((PROTOCOL_SCHEMA as any)['x-forbidden-properties'].map((item: unknown) => String(item).toLowerCase()));",
            "const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);",
            "const isForbiddenKey = (key: string) => { const lowered = key.toLowerCase(); return forbiddenProperties.has(lowered) || ['private_reasoning', 'raw_secret', 'api_key', 'access_token', 'authorization', 'cookie'].some((token) => lowered.includes(token)); };",
            "function scanForbidden(value: unknown, path: string): string[] { if (Array.isArray(value)) return value.flatMap((item, index) => scanForbidden(item, `${path}[${index}]`)); if (!isRecord(value)) return []; return Object.entries(value).flatMap(([key, child]) => [...(isForbiddenKey(key) ? [`${path}.${key} contains a forbidden security field`] : []), ...scanForbidden(child, `${path}.${key}`)]); }",
            "const resolveRef = (ref: string): JsonSchema => { const name = ref.split('/').pop() ?? ''; return (PROTOCOL_SCHEMA as any).$defs[name] as JsonSchema; };",
            "",
            "function validateNode(rule: JsonSchema, value: unknown, path: string): string[] {",
            "  if (rule.$ref) return validateNode(resolveRef(String(rule.$ref)), value, path);",
            "  const errors: string[] = [];",
            "  if (Array.isArray(rule.allOf)) for (const child of rule.allOf) errors.push(...validateNode(child, value, path));",
            "  if (Array.isArray(rule.anyOf)) { const branches = rule.anyOf.map((child: JsonSchema) => validateNode(child, value, path)); if (!branches.some((branch: string[]) => branch.length === 0)) errors.push(`${path} does not match any allowed shape`); }",
            "  if (Array.isArray(rule.oneOf)) { const branches = rule.oneOf.map((child: JsonSchema) => validateNode(child, value, path)); if (branches.filter((branch: string[]) => branch.length === 0).length !== 1) errors.push(`${path} does not match exactly one allowed shape`); }",
            "  if (rule.not && validateNode(rule.not, value, path).length === 0) errors.push(`${path} matches a forbidden shape`);",
            "  if (rule.type === 'object') {",
            "    if (!isRecord(value)) return [...errors, `${path} must be an object`];",
            "    for (const field of rule.required ?? []) if (!(field in value)) errors.push(`${path} is missing required field: ${field}`);",
            "    const properties = (rule.properties ?? {}) as Record<string, JsonSchema>;",
            "    for (const [key, child] of Object.entries(value)) { if (properties[key]) errors.push(...validateNode(properties[key], child, `${path}.${key}`)); else if (rule.additionalProperties === false) errors.push(`${path}.${key} is not allowed`); }",
            "  } else if (rule.type === 'array') {",
            "    if (!Array.isArray(value)) return [...errors, `${path} must be an array`];",
            "    if (rule.minItems !== undefined && value.length < Number(rule.minItems)) errors.push(`${path} must contain at least ${rule.minItems} item(s)`);",
            "    if (rule.items) value.forEach((item, index) => errors.push(...validateNode(rule.items, item, `${path}[${index}]`)));",
            "  } else if (rule.type === 'string') {",
            "    if (typeof value !== 'string') return [...errors, `${path} must be a string`];",
            "    if (rule.minLength !== undefined && value.length < Number(rule.minLength)) errors.push(`${path} is too short`);",
            "    if (rule.maxLength !== undefined && value.length > Number(rule.maxLength)) errors.push(`${path} is too long`);",
            "    if (rule.pattern && !(new RegExp(String(rule.pattern))).test(value)) errors.push(`${path} has an invalid format`);",
            "    if (rule.format === 'date-time' && Number.isNaN(Date.parse(value))) errors.push(`${path} must be an ISO date-time`);",
            "  } else if (rule.type === 'integer') {",
            "    if (typeof value !== 'number' || !Number.isInteger(value)) return [...errors, `${path} must be an integer`];",
            "    if (rule.minimum !== undefined && value < Number(rule.minimum)) errors.push(`${path} is below the minimum`);",
            "  } else if (rule.type === 'number') {",
            "    if (typeof value !== 'number' || Number.isNaN(value)) return [...errors, `${path} must be a number`];",
            "  } else if (rule.type === 'boolean' && typeof value !== 'boolean') return [...errors, `${path} must be a boolean`];",
            "  if (rule.enum && !(rule.enum as unknown[]).some((item) => Object.is(item, value))) errors.push(`${path} is not an allowed value`);",
            "  if (rule.const !== undefined && !Object.is(rule.const, value)) errors.push(`${path} must equal the schema constant`);",
            "  return errors;",
            "}",
            "",
            "export function validateProtocolPayload(kind: string, payload: unknown): ProtocolValidationResult {",
            "  const rule = (PROTOCOL_SCHEMA as any).$defs[kind] as JsonSchema | undefined;",
            "  if (!rule) return { ok: false, errors: [`Unknown protocol definition: ${kind}`] };",
            "  const errors = [...scanForbidden(payload, kind), ...validateNode(rule, payload, kind)];",
            "  return { ok: errors.length === 0, errors };",
            "}",
            "",
            "export function assertProtocolPayload<T>(kind: string, payload: unknown): T {",
            "  const verdict = validateProtocolPayload(kind, payload);",
            "  if (!verdict.ok) throw new Error(verdict.errors.join('; '));",
            "  return payload as T;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_outputs() -> tuple[str, str]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    schema_text = _canonical_json(schema)
    digest = hashlib.sha256(schema_text.encode("utf-8")).hexdigest()
    return _render_python(schema, schema_text, digest), _render_typescript(schema, schema_text, digest)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write generated projections")
    parser.add_argument("--check", action="store_true", help="fail when projections are stale")
    args = parser.parse_args(argv)
    if not args.write and not args.check:
        args.check = True
    expected_py, expected_ts = render_outputs()
    mismatches: list[str] = []
    for path, expected in ((PY_OUTPUT, expected_py), (TS_OUTPUT, expected_ts)):
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif actual != expected:
            mismatches.append(str(path.relative_to(REPO_ROOT)))
    if args.check and mismatches:
        print("stale generated protocol projections:")
        print("\n".join(f"- {item}" for item in mismatches))
        return 1
    if args.write:
        print(f"generated {PY_OUTPUT.relative_to(REPO_ROOT)}")
        print(f"generated {TS_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
