"""Build a bounded, provider-free developer-preview baseline evidence packet.

This checker summarizes already-produced deterministic package and update
rehearsal evidence.  It never builds, signs, publishes, downloads, installs,
or contacts a provider or update endpoint.  Its purpose is to keep the
currently demonstrable source-evaluation and packaging facts separate from an
unapproved public release.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SIDECAR_ROOT = REPO_ROOT / "apps" / "astrabridge-sidecar"

if str(SIDECAR_ROOT) not in sys.path:
    sys.path.insert(0, str(SIDECAR_ROOT))


REQUIRED_RELEASE_CHECKS = (
    "binding_evaluation",
    "updater_contract",
    "stage_a",
    "stage_b",
    "deterministic_comparison",
    "staged_binding_evaluation",
)

REQUIRED_REPORT_FIELDS = (
    "AstraBridge version or source commit",
    "operating system and relevant Python, Node, and package versions",
    "the exact no-key or package-validation command used",
    "expected result and actual result",
    "redacted reproduction steps and redacted diagnostics or screenshots",
    "whether the result reproduces without a provider credential",
)


def run_developer_preview_baseline_check(
    output_root: str | Path,
    *,
    release_readiness_summary: str | Path,
    windows_update_summary: str | Path,
    repo_root: str | Path = REPO_ROOT,
) -> dict[str, Any]:
    """Validate pre-release evidence and write a secret-free compact summary.

    The function intentionally expects successful evidence generated by the
    existing gates.  It does not turn their deterministic staging/rehearsal
    result into a claim that an installer, signing identity, update endpoint,
    security-reporting route, or public support channel is live.
    """

    repository = Path(repo_root).expanduser().resolve()
    root = Path(output_root).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise ValueError(f"Refusing to overwrite non-empty evidence root: {root}")
    root.mkdir(parents=True, exist_ok=True)

    release_path = Path(release_readiness_summary).expanduser().resolve()
    update_path = Path(windows_update_summary).expanduser().resolve()
    release = _read_json_object(release_path, label="release readiness summary")
    update = _read_json_object(update_path, label="Windows update rehearsal summary")

    release_evidence = _summarize_release_readiness(release, release_path, repository)
    update_evidence = _summarize_windows_update_rehearsal(update, update_path, repository)
    _require(
        release_evidence["release_version"] == update_evidence["release_version"],
        "Release-readiness and update-rehearsal evidence must name the same release version.",
    )

    policy = _read_current_pre_preview_policy(repository)
    evidence = {
        "schema_version": "astrabridge-developer-preview-baseline-evidence-v1",
        "mode": "deterministic_provider_free",
        "provider_calls": [],
        "network_calls_attempted": False,
        "source_evaluation": {
            "status": "demonstrated",
            "guide_path": "docs/NO_KEY_FIRST_TEN_MINUTES.md",
            "scope": "The documented route is an exact-source, no-provider, clean-clone fixture path. It creates AstraBridge-owned project state and demonstrates a bounded task-graph workflow.",
            "not_proved": [
                "a public installer or binary distribution",
                "live provider or model behavior",
                "coding-route eligibility, tool authority, or autonomous writes",
            ],
        },
        "package_contract": release_evidence,
        "update_rehearsal": update_evidence,
        "security_privacy": policy,
        "support": {
            "status": "pre_preview",
            "public_intake": "No public support commitment or issue-template triage route is configured by this baseline.",
            "required_report_fields": list(REQUIRED_REPORT_FIELDS),
            "sensitive_report_boundary": "Do not place vulnerability details, credentials, access tokens, cookies, authorization headers, raw provider requests, or personal data in a public report.",
        },
        "public_release": {
            "status": "blocked",
            "release_version": release_evidence["release_version"],
            "blockers": _current_public_release_blockers(),
        },
        "rollback": {
            "status": "rehearsal_passed",
            "proved": "The isolated staged canary rehearsal reached a committed candidate transaction and demonstrated rollback or commit recovery for four recorded interruption stages.",
            "not_proved": [
                "recovery of a published installer on an end-user machine",
                "availability of a public update endpoint or signed distribution",
                "a substitute for preserving redacted diagnostics and returning to a known-good source or artifact",
            ],
        },
        "claim_boundary": {
            "proved": "A developer can follow a documented no-key source-evaluation route, and maintainers can reproduce a deterministic release-identity/staging check plus an isolated Windows update-transaction rehearsal without provider or network calls.",
            "not_proved": [
                "a released or downloadable installer",
                "a live signed update service",
                "a configured private vulnerability-reporting route",
                "a configured private conduct-reporting route",
                "license or contribution terms for external merge-ready code",
                "a public maintainer support or issue-triage commitment",
            ],
        },
        "artifact_paths": {
            "evidence_json": "evidence.json",
            "evidence_markdown": "evidence.md",
        },
    }

    from astrabridge_sidecar.agentic_updates.contracts import assert_secret_free_agentic_update_payload

    assert_secret_free_agentic_update_payload(evidence, label="developer_preview_baseline")
    _write_json(root / "evidence.json", evidence)
    (root / "evidence.md").write_text(_render_markdown(evidence), encoding="utf-8", newline="\n")
    return evidence


def _summarize_release_readiness(
    summary: dict[str, Any], source_path: Path, repository: Path
) -> dict[str, Any]:
    _require(
        str(summary.get("schema_version") or "") == "astrabridge-release-readiness-v1",
        "Release readiness summary has an unexpected schema version.",
    )
    _require(str(summary.get("status") or "") == "pass", "Release readiness summary must pass.")
    release_version = str(summary.get("release_version") or "")
    _require(bool(release_version), "Release readiness summary must name a release version.")
    checks = dict(summary.get("checks") or {})
    for name in REQUIRED_RELEASE_CHECKS:
        _require(str(checks.get(name) or "") == "pass", f"Release readiness check must pass: {name}")

    staging_runs = dict(summary.get("staging_runs") or {})
    stage_a = dict(staging_runs.get("stage_a") or {})
    stage_b = dict(staging_runs.get("stage_b") or {})
    _require(str(stage_a.get("status") or "") == "pass", "Release stage A must pass.")
    _require(str(stage_b.get("status") or "") == "pass", "Release stage B must pass.")
    stage_a_count = int(stage_a.get("file_count") or 0)
    stage_b_count = int(stage_b.get("file_count") or 0)
    _require(stage_a_count > 0 and stage_a_count == stage_b_count, "Release staging inventories must be non-empty and equal.")

    return {
        "status": "pass",
        "evidence_type": "deterministic_release_identity_and_staging",
        "summary_reference": _safe_evidence_reference(source_path, repository),
        "release_version": release_version,
        "checks": {name: str(checks[name]) for name in REQUIRED_RELEASE_CHECKS},
        "staged_file_count_per_run": stage_a_count,
        "claim_limit": "This validates repository bindings and isolated staged contents. It is not a published, signed, or downloadable installer.",
    }


def _summarize_windows_update_rehearsal(
    summary: dict[str, Any], source_path: Path, repository: Path
) -> dict[str, Any]:
    _require(
        str(summary.get("schema_version") or "") == "astrabridge-windows-update-rehearsal-v1",
        "Windows update rehearsal summary has an unexpected schema version.",
    )
    _require(str(summary.get("status") or "") == "pass", "Windows update rehearsal summary must pass.")
    _require(str(summary.get("updater_contract_status") or "") == "pass", "Updater contract must pass.")
    release_version = str(summary.get("release_version") or "")
    _require(bool(release_version), "Windows update rehearsal summary must name a release version.")

    clean_install = dict(summary.get("clean_install_check") or {})
    update_check = dict(summary.get("update_check") or {})
    rollback_check = dict(summary.get("rollback_check") or {})
    recovery_matrix = dict(summary.get("recovery_matrix") or {})
    for name, value in (
        ("clean install", clean_install),
        ("update", update_check),
        ("rollback", rollback_check),
        ("recovery matrix", recovery_matrix),
    ):
        _require(str(value.get("status") or "") == "pass", f"Windows update rehearsal {name} check must pass.")
    _require(str(update_check.get("transaction_status") or "") == "committed", "Update transaction must commit in the rehearsal.")
    scenarios = list(recovery_matrix.get("scenarios") or [])
    _require(len(scenarios) >= 1, "Recovery matrix must contain at least one scenario.")
    _require(
        all(str(dict(scenario).get("status") or "") == "pass" for scenario in scenarios),
        "Every recovery scenario must pass.",
    )

    return {
        "status": "pass",
        "evidence_type": "isolated_windows_update_transaction_rehearsal",
        "summary_reference": _safe_evidence_reference(source_path, repository),
        "release_version": release_version,
        "selected_channel": str(summary.get("selected_channel") or ""),
        "checks": {
            "updater_contract": "pass",
            "clean_install": "pass",
            "update_transaction": "pass",
            "rollback": "pass",
            "recovery_matrix": "pass",
        },
        "recovery_scenario_count": len(scenarios),
        "claim_limit": "This is an isolated deterministic transaction rehearsal. It does not contact a public endpoint or prove a published signed installer.",
    }


def _read_current_pre_preview_policy(repository: Path) -> dict[str, Any]:
    security_path = repository / "SECURITY.md"
    conduct_path = repository / "CODE_OF_CONDUCT.md"
    foundation_path = repository / "docs" / "OPEN_SOURCE_FOUNDATION_DECISION_RECORD.md"
    no_key_path = repository / "docs" / "NO_KEY_FIRST_TEN_MINUTES.md"
    isolation_path = repository / "docs" / "SECURITY_AND_ISOLATION.md"
    for path in (security_path, conduct_path, foundation_path, no_key_path, isolation_path):
        _require(path.is_file(), f"Required pre-preview policy file is missing: {path.name}")

    security_text = security_path.read_text(encoding="utf-8")
    conduct_text = conduct_path.read_text(encoding="utf-8")
    has_license = any((repository / name).is_file() for name in ("LICENSE", "LICENSE.md", "LICENSE.txt"))
    _require(not has_license, "This pre-preview baseline is only valid while the root license remains owner-gated.")
    _require(
        "private vulnerability-reporting channel\nhas not yet been configured" in security_text,
        "SECURITY.md must keep the missing private vulnerability route explicit for this baseline.",
    )
    _require(
        "No private conduct-reporting contact has been configured yet." in conduct_text,
        "CODE_OF_CONDUCT.md must keep the missing private conduct route explicit for this baseline.",
    )

    return {
        "status": "actionable_pre_preview_boundary",
        "normal_project_state": [".abproj", ".astrabridge/"],
        "guidance_paths": [
            "docs/SECURITY_AND_ISOLATION.md",
            "SECURITY.md",
            "docs/OPEN_SOURCE_FOUNDATION_DECISION_RECORD.md",
        ],
        "credential_boundary": "Do not persist plaintext provider credentials, official Codex configuration, or raw secret-bearing transport data in project state, logs, screenshots, or reports.",
        "provider_boundary": "Provider calls are optional and explicitly authorized; the source evaluation and package/update evidence summarized here made no provider call.",
        "unresolved_reporting_routes": [
            "private vulnerability reporting",
            "private conduct reporting",
        ],
    }


def _current_public_release_blockers() -> list[dict[str, str]]:
    return [
        {
            "id": "license_and_contribution_terms",
            "owner": "project and legal foundation owner",
            "required_action": "Choose the license, confirm copyright ownership, define contribution terms, and complete third-party notice review.",
        },
        {
            "id": "private_vulnerability_reporting",
            "owner": "security maintainer",
            "required_action": "Configure and test one private vulnerability-reporting route, name a response owner, and publish supported-version policy.",
        },
        {
            "id": "private_conduct_reporting",
            "owner": "conduct enforcement owner",
            "required_action": "Configure a monitored private conduct-reporting contact and state the response expectation.",
        },
        {
            "id": "public_support_and_issue_triage",
            "owner": "community and maintainer-triage owner",
            "required_action": "Keep the prepared safe templates, reproducible report route, and future triage expectation disabled until the license, private reporting routes, explicit maintainer owner, and repository-host intake settings are verified.",
        },
        {
            "id": "authorized_distribution_release",
            "owner": "release owner",
            "required_action": "Approve signing, distribution, installer clean-user validation, artifact provenance, and a real release evidence note before publication.",
        },
    ]


def _safe_evidence_reference(path: Path, repository: Path) -> str:
    try:
        return path.relative_to(repository).as_posix()
    except ValueError:
        return "external-input-redacted"


def _read_json_object(path: Path, *, label: str) -> dict[str, Any]:
    _require(path.is_file(), f"Missing {label}: {path}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid {label} JSON: {path}") from exc
    _require(isinstance(value, dict), f"{label.capitalize()} must be a JSON object.")
    return dict(value)


def _render_markdown(evidence: dict[str, Any]) -> str:
    package = dict(evidence.get("package_contract") or {})
    update = dict(evidence.get("update_rehearsal") or {})
    release = dict(evidence.get("public_release") or {})
    return "\n".join(
        [
            "# Developer Preview Baseline Evidence",
            "",
            f"- Mode: {evidence.get('mode')}",
            f"- Source evaluation: {dict(evidence.get('source_evaluation') or {}).get('status')}",
            f"- Package contract: {package.get('status')} ({package.get('release_version')})",
            f"- Update rehearsal: {update.get('status')} ({update.get('selected_channel')})",
            f"- Public release: {release.get('status')}",
            f"- Release blockers: {len(list(release.get('blockers') or []))}",
            "",
            "This packet records a bounded source-evaluation path plus deterministic staging and isolated update-transaction evidence. It is not a release authorization or a public installer claim.",
            "",
        ]
    )


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write a bounded AstraBridge developer-preview baseline evidence packet.")
    parser.add_argument("--release-readiness-summary", type=Path, required=True)
    parser.add_argument("--windows-update-summary", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args(argv)
    evidence = run_developer_preview_baseline_check(
        args.output_root,
        release_readiness_summary=args.release_readiness_summary,
        windows_update_summary=args.windows_update_summary,
    )
    print(
        {
            "source_evaluation": dict(evidence["source_evaluation"]).get("status"),
            "package_contract": dict(evidence["package_contract"]).get("status"),
            "update_rehearsal": dict(evidence["update_rehearsal"]).get("status"),
            "public_release": dict(evidence["public_release"]).get("status"),
            "evidence": str((args.output_root / "evidence.json").resolve()),
        }
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
